/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_billthefarmer_sudoku_Sudoku */

#ifndef _Included_org_billthefarmer_sudoku_Sudoku
#define _Included_org_billthefarmer_sudoku_Sudoku
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_billthefarmer_sudoku_Sudoku
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_billthefarmer_sudoku_Sudoku_init
  (JNIEnv *, jobject);

/*
 * Class:     org_billthefarmer_sudoku_Sudoku
 * Method:    process
 * Signature: ([BIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_billthefarmer_sudoku_Sudoku_process
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint);

/*
 * Class:     org_billthefarmer_sudoku_Sudoku
 * Method:    getAngle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_billthefarmer_sudoku_Sudoku_getAngle
  (JNIEnv *, jobject);

/*
 * Class:     org_billthefarmer_sudoku_Sudoku
 * Method:    getRect
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_billthefarmer_sudoku_Sudoku_getRect
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     org_billthefarmer_sudoku_Sudoku
 * Method:    getPuzzle
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_billthefarmer_sudoku_Sudoku_getPuzzle
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     org_billthefarmer_sudoku_Sudoku
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_billthefarmer_sudoku_Sudoku_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
